version: "3.9"

services:

  api-gateway:
    image: ibkd/api-gateway:latest
    build:
      context: ../api-gateway/implementation
      dockerfile: Dockerfile
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -f  http://localhost:8080/actuator/health || exit 1" ]
      interval: 1m
      timeout: 30s
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 256m
