version: "3.9"

services:

  discovery:
    image: infobip-kulendayz/discovery-service:latest
    build:
      context: ../discovery
      dockerfile: Dockerfile
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -f  http://localhost:8761/actuator/health || exit 1" ]
      interval: 1m
      timeout: 30s
    environment:
      - SPRING_SERVER_PORT=8761
    ports:
      - "127.0.0.1:8761:8761"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 256m
