version: "3.9"

services:

  haproxy:
    image: haproxy:lts-alpine
    ports:
      - "80:80"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 256m

