version: "3.9"

volumes:
  postgres-data:
    name: postgres-data

services:

  postgres:
    image: postgres:15.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres || exit 1" ]
      interval: 1m
      timeout: 30s
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d:ro
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 1024m
        reservations:
          memory: 512m

