version: "3.9"

services:

  user-management:
    image: infobip-kulendayz/user-management:latest
    build:
      context: ../user-management/implementation
      dockerfile: Dockerfile
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -f  http://localhost:8080/actuator/health || exit 1" ]
      interval: 1m
      timeout: 30s
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 256m
