version: "3.9"

services:

  zipkin:
    image: openzipkin/zipkin:2
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "docker-healthcheck" ]
      interval: 1m
      timeout: 30s
    ports:
      - "127.0.0.1:9411:9411"
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 256m
        reservations:
          memory: 256m

