server:

  error:
    whitelabel:
      enabled: false

spring:

  application:
    name: api-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
        - StripPrefix=1
      routes:
        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: user-management-route
          uri: lb://user-management
          predicates:
            - Path=/api/user/**
        - id: infobip-integration-route
          uri: lb://infobip-integration
          predicates:
            - Path=/api/infobip/**

eureka:
  instance:
    prefer-ip-address: true
    metadataMap:
      "prometheus.path": "/actuator/prometheus"
  client:
    initial-instance-info-replication-interval-seconds: 1
    instance-info-replication-interval-seconds: 2
    registry-fetch-interval-seconds: 2
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

management:
  info:
    env:
      enabled: true
    java:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, prometheus, info

info:
  app:
    name: API Gateway
    description: API Gateway service
