server:
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: user-management

  datasource:
    url: jdbc:postgresql://postgres:5432/user_mgmt
    username: user_mgmt_user
    password: user_mgmt_user
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              create-target: ./target/generated_schema.sql
              action: create
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        generate_statistics: false
        format_sql: false
        connection:
          charSet: UTF-8

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/master.yml
    drop-first: false

  zipkin:
    baseUrl: http://zipkin:9411

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ibkd_user_mgmt_user
    password: ibkd_user_mgmt_user
    virtual-host: infobip-kulendayz

eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      "prometheus.path": "/actuator/prometheus"
  client:
    initial-instance-info-replication-interval-seconds: 2
    instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 10
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  info:
    env:
      enabled: true
    java:
      enabled: true
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health, prometheus, info

info:
  app:
    name: User Management
    description: User Management service

jwt:
  claims:
    issuer: Infobip @ KulenDayz 2023
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  validity: 3600
