global:
  scrape_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  - job_name: 'Infobip Kulendayz Services via Eureka'
    eureka_sd_configs:
    - server: http://discovery:8761/eureka
      refresh_interval: 30s
    relabel_configs:
    - source_labels: [__meta_eureka_app_name]
      target_label: application
    - source_labels: [__meta_eureka_app_instance_metadata_prometheus_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    - source_labels: [__address__]
      target_label: instance

  - job_name: 'RabbitMq'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['rabbitmq:15692']
